"Plugins
call plug#begin('~/.vim/plugged')
Plug 'flazz/vim-colorschemes'
Plug 'Valloric/YouCompleteMe'
Plug 'scrooloose/nerdtree'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'tpope/vim-surround'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'christoomey/vim-system-copy'
Plug 'ludovicchabant/vim-gutentags'
call plug#end()

"VIM colorscheme
colorscheme molokai

syntax on
set hlsearch
set number
set ruler
set backspace=2

set expandtab
set smarttab
set shiftround
set shiftwidth=4

:command! W w
:command! Q q
:command! Wq wq
:command! WQ wq

"Set leader to comma
let mapleader = ","
inoremap '' <ESC>
nnoremap <CR> o<ESC>
nnoremap <C-S> :update<CR>
inoremap <C-S> <ESC>:update<CR>gi
noremap :ne :NERDTreeToggle
map <leader>c :nohlsearch<CR>
nnoremap <leader>re :edit $MYVIMRC<CR>
nnoremap <leader>rs :source $MYVIMRC<CR>

:set number relativenumber
:augroup numbertoggle
:  autocmd!
:  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
:  autocmd BufLeave,FocusLost,InsertEnter * set norelativenumber
:augroup END

"YCM setting
let g:ycm_autoclose_preview_window_after_completion=1

"NERDTree setting
set wildignore+=*/tmp/*,*.so,*.swp,*.zip

"Use system clipboard for * register
set clipboard+=unnamedplus

"ctags
set tags=./tags;,tags
